apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-webserver
spec:
  serviceName: nginx-webserver
  replicas: 1
  selector:
    matchLabels:
      app: nginx-webserver
  template:
    metadata:
      labels:
        app: nginx-webserver
    spec:
      imagePullSecrets:
        - name: github-secret
      containers:
        - name: nginx
          image: "{{ .Values.statefulset.image.repository }}:{{ .Values.statefulset.image.tag }}"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          emptyDir: {}
