apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-webserver
spec:
  serviceName: nginx-webserver
  replicas: 1
  selector:
    matchLabels:
      app: nginx-webserver
  template:
    metadata:
      labels:
        app: nginx-webserver
    spec:
      containers:
        - name: nginx
          image: ghcr.io/huskyishere/nginx-webserver:latest  # Replace with your image
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          emptyDir: {}
