apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-webserver
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: nginx-webserver=ghcr.io/ditthapeem/nginx-webserver:latest
    argocd-image-updater.argoproj.io/nginx-webserver.update-strategy: digest
    argocd-image-updater.argoproj.io/nginx-webserver.pull-secret: secret:argocd/argo-secret#github-package
  finalizers:
  - resources-finalizer.argocd.argoproj.io

spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    helm:
      releaseName: nginx-webserver
      parameters:
        - name: image.tag
          value: latest
    path: helm/nginx-webserver
    repoURL: 'https://github.com/Ditthapeem/statefulset-nginx-webserver.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
